### ISSUE TITLE
[FEATURE] Reporting CLI

### ISSUE THREAD

**Issue by davidcui1225** [opensearch-project/reporting#345]
## Overview

Currently, Reporting does not have any quick out-of-box options to be able to download reports. Users have to download from OpenSearch Dashboards itself with the plugin installed. Reporting Anything provides users with a Reporting CLI to be able to download reports without requiring the use of Dashboards and the Dashboards plugin.

## Feature Suggestion

When users encounter issues using the Dashboards plugin, there is no work-around aside from a code change that can enable report downloads. Additionally, users with a specific use case for reporting will have a convenient option to download reports directly. Customers will be able to integrate this CLI component into their own workflows/environments to bypass any authentication or security issues. 

User Quote - "The current manually generated csv and pdf reports are nice but it’d be great to be able to automate and send these via email or even just fetch via an API request."

## Requirements

* Provide a CLI option for downloading reports
* Enable users to set parameters

## Out of scope
* Support for scheduled reports
* Saved search reports 

### Solution overview
Reporting Anything's solution is to provide a mechanism for users to be able to download reports independent of the plugin. It will also provide extensibility in that users can create a report from anything by providing a URL, and are not limited to the report source options provided in the reporting plugin. 

### Proposed Solution
The proposed solution is to provide a CLI option. Users will be able to work around authentication issues by integrating into their own workflows. For example, a user running Reporting Anything in an AWS Lambda instance will not have to deal with any security issues that they would running the Reporting plugin in OpenSearch Dashboards. From there, the user can also integrate with an email service to create an email report mechanism. 

### User interface
The user interface will be on the command line, with the user being given several parameters, including:
* Saved object ID (for OpenSearch Dashboards reports)
* Report source type (Dashboard, visualization, saved search)
* Full URL of the report
* File format for download (PDF or PNG, default is PDF)
* Window width in pixels (default is 1680)
* Window height in pixels (default is 2560)

Sample commands:
```
reporting-anything --object-id 7adfa750-4c81-11e8-b3d7-01146121b73d --format pdf 
```

```
 reporting anything --url http://localhost:5601/app/dashboards#/view/7adfa750-4c81-11e8-b3d7-01146121b73d?_g=(filters:!(),refreshInterval:(pause:!f,value:900000),time:(from:now-24h,to:now))&_a=(description:'Analyze%20mock%20flight%20data%20for%20OpenSearch-Air,%20Logstash%20Airways,%20OpenSearch%20Dashboards%20Airlines%20and%20BeatsWest',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'%5BFlights%5D%20Global%20Flight%20Dashboard',viewMode:view) --format png
```

### Component design
The only component of the project is the command line interface, which contains all the functionality for reporting anything. The design of the CLI is in the above section.

**Comment by joshuali925** [comment]
it would be good if we could list some difference/advantages over just using chrome binary to save screenshots
e.g.
```bash
chromium --headless --screenshot=report.png https://www.google.com
chromium --headless --print-to-pdf=report.pdf https://www.google.com
```

**Comment by davidcui1225** [comment]
> it would be good if we could list some difference/advantages over just using chrome binary to save screenshots e.g.
> 
> ```shell
> chromium --headless --screenshot=report.png https://www.google.com
> chromium --headless --print-to-pdf=report.pdf https://www.google.com
> ```
> 
> object id and filters are part of URL, the only difference seems to be supporting csv reports

Good point, the scope of this should increase to at least include email reports then.

**Comment by abbashus** [comment]
- Is **Anything** a placeholder for actual coming soon name?
- _"without requiring the use of Dashboards"_ : Is it possible to do without Dashboards? 🤔 

As a thought, we should be publishing a library that includes the mentioned functionality, and CLI being just a wrapper on top of it. This way we can use it in serverless environments like AWS Lambda, Azure Functions etc or any other app.

**Comment by davidcui1225** [comment]
> * Is **Anything** a placeholder for actual coming soon name?
> 
>     * _"without requiring the use of Dashboards"_ : Is it possible to do without Dashboards? 🤔
> 
> 
> As a thought, we should be publishing a library that includes the mentioned functionality, and CLI being just a wrapper on top of it. This way we can use it in serverless environments like AWS Lambda, Azure Functions etc or any other app.

`Anything` is just a placeholder name, yes. Also without requiring the use of Dashboards was meant to convey "without requiring navigation to the OpenSearch Dashboards front-end."

I agree that publishing a library is probably the best path forward. I think we will have a clearer picture of what functionalities customers will want next week. A good baseline is likely the mentioned features above, and email reports.

**Comment by vamsi-amazon** [comment]
> When users encounter issues using the Dashboards plugin, there is no work-around aside from a code change that can enable report downloads.

Wont this be same with cli command? Any issue with report generation logic would need up gradation of command. Also it is mentioned in the design section that we will be packaging the existing plugin code into a command.


> User Quote - "The current manually generated csv and pdf reports are nice but it’d be great to be able to automate and send these via email or even just fetch via an API request."

From the above statement what I understood is User wants to avoid all the possible manual touch points in fetching the reports. Probably, the API request is also for automating the process themselves. What I couldn't understand is How does having CLI command will solve this problem?

Installing CLI command vs installing opensearch plugins.
Manually writing commands vs Manually triggering UI commands.
I might be missing something here. Why can't we build and enhance automated report generation features.

**Comment by davidcui1225** [comment]
> Wont this be same with cli command? Any issue with report generation logic would need upgradation of command. Also it is mentioned in the design section that we will be packaging the existing plugin code into a command.

Not quite- the issue is not with the logic of the report generation itself. It is with other functionalities reporting is meant to provide, such as emailing of reports. Some customers have also run into authentication issues. 

> From the above statement what I understood is User wants to avoid all the possible manual touch points in fetching the reports. Probably, the API request is also for automating the process themselves. What I couldn't understand is How does having CLI command will solve this problem?

The email use case is one that we should plan to add. The CLI interface's initial thought was for users who were running into authentication issues, and those who wanted email support. But it will be easier to dive into this conversation further once we get more user feedback.

> Installing CLI command vs installing opensearch plugins.
Manually writing commands vs Manually triggering UI buttons.
I might be missing something here. Why can't we build and enhance automated report generation features.

We can, but for a CLI interface automated report generation, particularly for scheduled reports, could be tricky because it would require the server to be continuously running. Automated report generation is supported in the current Dashboards plugin in the form of scheduled report definitions.

**Comment by ps48** [comment]
This is nice proposal! I have a some questions about the motivation and the proposed solution.

> When users encounter issues using the Dashboards plugin, there is no work-around aside from a code change that can enable report downloads. 

1. What issues do users have with the current reporting plugin? What work around/code changes do they make to get things running? If these issues are common, can't we just provide configurations for them in `dashboards.yml` config file?

> User Quote - "The current manually generated csv and pdf reports are nice but it’d be great to be able to automate and send these via email or even just fetch via an API request."

2. From the quote it appears like users need more of automation/email and API enpoints. How much of this will get solved with upcoming [notifications](https://github.com/opensearch-project/notifications) plugin? 

3. Why do we propose CLI tool as a solution (and not APIs)? Shouldn't a simpler solution be to expose APIs re-using the existing ones from dashboards node backend? 

4. How would the CLI tool work with permissions/user access and security plugin? 

5. Is "Reporting Anything" still restricted to be used within the OpenSearch realm? If not, how do we plan to replace the existing scheduler dependency?

**Comment by davidcui1225** [comment]
> What issues do users have with the current reporting plugin? What work around/code changes do they make to get things running? If these issues are common, can't we just provide configurations for them in dashboards.yml config file?

Most of the issues we are trying to address  here are related to authentication in Opensearch and  Dashboards core. These issues have been encountered by several customers but the scope of the fix is too large for a config file change.

> From the quote it appears like users need more of automation/email and API enpoints. How much of this will get solved with upcoming [notifications](https://github.com/opensearch-project/notifications) plugin?

The original issue needs to be updated to reflect the customer need more accurately. Essentially by providing Reporting Anything, customers can integrate it into their own workflows however they want to bypass auth issues (e.g AWS Lambda), which is not in scope of Notifications.

> Why do we propose CLI tool as a solution (and not APIs)? Shouldn't a simpler solution be to expose APIs re-using the existing ones from dashboards node backend?

An API is an option, but for providing customers a method to download reports within their own workflow is more convenient with a simple CLI that takes in a handful of parameters. 

> How would the CLI tool work with permissions/user access and security plugin?

That should be entirely up to the discretion of the user- ideally, since they would be running this workflow from their own environment, they shouldn't be encountering any auth/security issues. 

> Is "Reporting Anything" still restricted to be used within the OpenSearch realm? If not, how do we plan to replace the existing scheduler dependency?

Reporting Anything is a generic CLI tool that can be used to download a report of anything. It will have CLI parameters for OpenSearch users (e.g saved object ID, report source), but non-OpenSearch pages can be downloaded as reports as well with the  URL parameter. There is no plan to add a scheduler component at this time.

**Comment by joshuali925** [comment]
A few questions for this project:

> Most of the issues we are trying to address here are related to authentication in Opensearch and Dashboards core.

Could you link some issues that needs reporting anything for cross reference?

> since they would be running this workflow from their own environment, they shouldn't be encountering any auth/security issues.

Auth depends on credentials provided, why they won't have issues if this runs in their environment (and what does "their own environment" mean)? e.g. how do you pass credentials from user to cli, and from cli to Dashboards?

> An API is an option, but for providing customers a method to download reports within their own workflow is more convenient with a simple CLI that takes in a handful of parameters.

CLI requires installation and is not cross platform. API is just a http call, which also accepts parameters. Why is CLI more convenient?

**Comment by davidcui1225** [comment]
Demo of Reporting Anything
https://user-images.githubusercontent.com/53581635/165551551-0f4d4e6f-e89c-4636-91e1-1f5df6b36cb3.mp4

**Comment by davidcui1225** [comment]
Updated demo video to use CLI wrapper

**Comment by davidcui1225** [comment]
### Remaining Work Breakdown Structure
#### Authentication Issues
* Access security-enabled dashboards cluster from Reporting Anything (TBD)

#### Chromium & Automation 
* Bundle chromium to automatically install on user machine for downloading 
* Add script to install dependencies and CLI wrapper 

#### Testing & Documentation
* Test on security-enabled OpenSearch Dashboards cluster with report sources
* Write all/make any changes to required documentation on reporting-anything (e.g README, SECURITY, CONTRIBUTING, etc.)

**Comment by davidcui1225** [comment]
### SOP for installing & running reporting-anything:
```
git clone git@github.com:davidcui1225/dashboards-reports.git
cd dashboards-reports
git checkout reporting-anything
cd reporting-anything/src
```
* Download chromium zip from [here](https://github.com/davidcui1225/dashboards-reports/releases/tag/reporting-anything), unzip in the `reporting-anything` directory
```
node download_report.js -u <url>
```

For additional command line parameter options, run with `-h` flag

**Comment by sumukhswamy** [comment]
Auth types for CLI
*HTTP authentication in Open Search*

These are the allowed values for type:
basic: HTTP basic authentication. No additional configuration is needed.
kerberos: Kerberos authentication. Additional, Kerberos-specific configuration is needed.
jwt: JSON web token authentication. Additional, JWT-specific configuration is needed.
clientcert: Authentication through a client TLS certificate. This certificate must be trusted by one of the root CAs in the truststore of your nodes.
After setting an HTTP authenticator, you must specify against which backend system you want to authenticate the user:
noop: No further authentication against any backend system is performed. Use noop if the HTTP authenticator has already authenticated the user completely, as in the case of JWT, Kerberos, or client certificate authentication.
internal: Use the users and roles defined in internal_users.yml for authentication.
ldap: Authenticate users against an LDAP server. This setting requires additional, LDAP-specific configuration settings.


*HTTP basic*

The security plugin sends a response with status UNAUTHORIZED (401) back to the client. If the client is accessing the cluster with a browser, this triggers the authentication dialog box, and the user is prompted to enter a user name and password.
*Kerberos* 
Kerberos authentication does not work with OpenSearch Dashboards. To track OpenSearch’s progress in adding support for Kerberos in OpenSearch Dashboards, see [issue #907 Kerberos Auth does not exist](https://github.com/opensearch-project/security-dashboards-plugin/issues/907) (https://github.com/opensearch-project/security-dashboards-plugin/issues/907) in the Dashboard’s Security Plugin repository. {: .warning }

*JSON web token*

JSON web tokens (JWTs) are JSON-based access tokens that assert one or more claims. They are commonly used to implement single sign-on (SSO) solutions and fall in the category of token-based authentication systems:
A user logs in to an authentication server by providing credentials (for example, a user name and password).
The authentication server validates the credentials.
The authentication server creates an access token and signs it.
The authentication server returns the token to the user.
The user stores the access token.
The user sends the access token alongside every request to the service that it wants to use.
The service verifies the token and grants or denies access.
A JSON web token is self-contained in the sense that it carries all necessary information to verify a user within itself. The tokens are base64-encoded, signed JSON objects.
JSON web tokens consist of three parts:
Header
Payload
Signature

*Header*

The header contains information about the used signing mechanism, as shown in the following example:
{
 "alg": "HS256",
 "typ": "JWT"
}
 
In this case, the header states that the message was signed using HMAC-SHA256.

*Payload*

The payload of a JSON web token contains the so-called JWT Claims. A claim can be any piece of information about the user that the application that created the token has verified.
The specification defines a set of standard claims with reserved names (“registered claims”). These include, for example, the token issuer, the expiration date, or the creation date.
Public claims, on the other hand, can be created freely by the token issuer. They can contain arbitrary information, such as the user name and the roles of the user.
Example:
{
 "iss": "example.com",
 "exp": 1300819380,
 "name": "John Doe",
 "roles": "admin, devops"
}
 

*Signature*

The issuer of the token calculates the signature of the token by applying a cryptographic hash function on the base64-encoded header and payload. These three parts are then concatenated using periods to form a complete JSON web token:
encoded = base64UrlEncode(header) + "." + base64UrlEncode(payload)
signature = HMACSHA256(encoded, 'secretkey');
jwt = encoded + "." + base64UrlEncode(signature)






*JSON web token*

jwt_auth_domain:
 enabled: true
 order: 0
 http_authenticator:
 type: jwt
 challenge: false
 config:
 signing_key: "base64 encoded key"
 jwt_header: "Authorization"
 jwt_url_parameter: null
 subject_key: null
 roles_key: null
 authentication_backend:
I type: noop


 Algorithms for the signing_key: Symmetric - HMAC Asymmetric - RSA and ECDSA

**Comment by davidcui1225** [comment]
> ### SOP for installing & running reporting-anything:
> 
> ```
> git clone git@github.com:davidcui1225/dashboards-reports.git
> cd dashboards-reports
> git checkout reporting-anything
> cd reporting-anything/src
> ```
> 
>     * Download chromium zip from [here](https://github.com/davidcui1225/dashboards-reports/releases/tag/reporting-anything), unzip in the `reporting-anything` directory
> 
> 
> ```
> node download_report.js -u <url>
> ```
> 
> For additional command line parameter options, run with `-h` flag

The link to the chromium bundle should be public. FYI that link provided is for Macos-x64 chromium. The other chromium links can be found [here](https://github.com/opendistro-for-elasticsearch/kibana-reports/releases/tag/chromium-1.12.0.0)

**Comment by sumukhswamy** [comment]
<img width="846" alt="image" src="https://user-images.githubusercontent.com/107440906/178063084-6b956e42-3eb9-4ec4-a0c3-be34ead6f4a9.png">

**Comment by sumukhswamy** [comment]
![2B6D3B91-2EFA-4D07-B129-44A0AED9C7B2_1_102_o](https://user-images.githubusercontent.com/107440906/178063650-3b44a6cc-8604-4b42-b467-e12fd213ebd3.jpeg)

**Comment by sumukhswamy** [comment]
Cognito auth demo 
The third party authentication is provided with Cognito where the below video shows how the authentication is done.
-a authentication flag indicates the type of authentication type and performs the necessary login with the credentials provided
-u is the url to the dashboard
-c takes username:password

https://user-images.githubusercontent.com/107440906/178854168-c11f9cf6-59a7-4c60-8fb6-33086837d129.mp4

**Comment by sumukhswamy** [comment]
https://quip-amazon.com/1NbZAIS9UiIK/Test-cases-for-auth-cli 
test case document

**Comment by zhongnansu** [comment]
> https://quip-amazon.com/1NbZAIS9UiIK/Test-cases-for-auth-cli test case document

@sumukhswamy We don't post Amazon private links to github. Please delete your comment.

**Comment by joshuali925** [comment]
thanks @zhongnansu 

@sumukhswamy I removed your comment, we don't post amazon links here

**Comment by anirudha** [comment]
> @davidcui1225 @sumukhswamy
> 
> `reporting-anything` works goods, theres any plan to merge this "tool" to `main` branch?

soon, this will go to main, ~2-4weeks

**Comment by sumukhswamy** [comment]
SOP for installing & running reporting-anything:

git@github.com:sumukhswamy/dashboards-reports.git
cd dashboards-reports
git checkout reporting-anything
cd reporting-anything/src



* Download chromium zip from [here](https://github.com/davidcui1225/dashboards-reports/releases/tag/reporting-anything), unzip in the `reporting-anything` directory

reporting-anything -u <url>
other flags which can be used -n(name of the file), -a(authentication type), -h (height of the file), w(width of the file)
-a cognito → for cognito
-a SAML → for SAML
no need to mention any flag for FGAC
Before running the code a .env file with the username and password needs to be specified as follows
[Image: Image.jpg]
The test case document for the same is linked here https://quip-amazon.com/1NbZAIS9UiIK

https://github.com/opensearch-project/dashboards-reports/pull/392

The email/username which needs to receive emails needs to be first verified by SES or will throw an error.

the template for the email is to be stored src/views

**Comment by Sandy381** [comment]
Opensearch Reporting scheduler not working with E-mails.
Cannot schedule reports.

**Comment by rupal-bq** [comment]
https://user-images.githubusercontent.com/56703525/201599325-07ed7a51-b66c-48cd-86a5-238008a8b871.mov

**Comment by anirudha** [comment]
@elfisher cli delivery is version independent. i'll remove the version tag on this.

**Comment by alicejw-aws** [comment]
Question: I'm inferring from the Cognito and SAML demos that it's possible to simply download the file instead of requesting an email, is this correct? Thanks 
(i thought that email transport was the default delivery method - just want to verify for the documentation)

**Comment by fymaterials98** [comment]
How to install this report-anything?
`git clone git@github.com:davidcui1225/dashboards-reports.git
cd dashboards-reports
git checkout reporting-anything
cd reporting-anything/src`
I did this step.  Do I need to download chromium zip to reporting-anything directory?
I saw this instruction
1 
[git@github.com](mailto:git@github.com):sumukhswamy/dashboards-reports.git
cd dashboards-reports
git checkout reporting-anything
cd reporting-anything/src
2
Download chromium zip from [here](https://github.com/davidcui1225/dashboards-reports/releases/tag/reporting-anything), unzip in the reporting-anything directory
3
reporting-anything -u

Do I need to do 1, 2 and 3? What does step 3 do?

Thanks,
Arthur

**Comment by joshuali925** [comment]
@fymaterials98 thanks for your interest. Reporting-cli release is currently in progress (https://github.com/opensearch-project/opensearch-build/issues/3112)

If you want to try it now you can follow [developer instructions](https://github.com/opensearch-project/reporting-cli/blob/main/DEVELOPER_GUIDE.md#sop-for-installing-and-running-reporting-cli) steps 1-3 to install and [user guide](https://github.com/opensearch-project/reporting-cli/blob/main/USER_GUIDE.md) to use

After it gets released it can be installed from npm directly.

**Comment by rupal-bq** [comment]
Hi, [opensearch-reporting-cli](https://www.npmjs.com/package/@opensearch-project/reporting-cli) is released. Please check https://opensearch.org/docs/latest/dashboards/reporting-cli/rep-cli-index/ for more information.
