### ISSUE TITLE
[FEATURE] Discover Reporting - included timestamp field when generating CSV

### ISSUE THREAD

**Issue by ryn9** [opensearch-project/reporting#668]
**Is your feature request related to a problem?**
N/A

**What solution would you like?**
Currently - when generating a CSV from Discover, the timestamp is not included in the output.
Please include the displayed timestamp in the output.

**What alternatives have you considered?**
manually adding the timestamp to the display fields, therefore displaying the time twice in Discover, but only once in the output is what I have been using to work around this limitation.

**Do you have any additional context?**
N/A

**Comment by joshuali925** [comment]
@ryn9 i believe this is what you meant, correct me if i'm wrong: discover displays an additional `Time` column regardless of fields selected. this extra logic is not in reporting, so it only shows selected fields

i'm currently working on something else and i'll see when i can get to this. if you are interested, feel free to take a look and send a PR. i think here we need to include the time field into selected fields
https://github.com/opensearch-project/dashboards-reporting/blob/df8b413ae12ee6ac237392246a9da4e5e858eac5/server/routes/utils/dataReportHelpers.ts#L148

**Comment by ryn9** [comment]
@joshuali925 - any update on this ?

**Comment by henceiam** [comment]
@joshuali925 I am also curious if there is any plans for this?

**Comment by zawadaa** [comment]
Exporting to CSV without timestamps in most cases are useless :-(

**Comment by joshuali925** [comment]
there is a workaround by adding the time field into the saved search selected fields. it worked for me
1. open the saved search in discover
1. open network tab of browser dev tool
1. click on "Save" to save the search again
1. In the network requests tab, filter by `api/saved_objects/search`, there should be one match
1. right click on it, then click copy -> copy as fetch
1. go to Console tab of the browser dev tool, paste
1. look for the line starts with `"body": `, there should be a `"columns"` part. add `\"<time-field-name>\"` as the first element of the value. for example it might be
   ```
   ...\"columns\":[\"agent.id\",\"@version\"],...
   ```
    And the time field i want to include is called `@timestamp`, I would modify this part to be
    ```
    ...\"columns\":[\"@timestamp\",\"agent.id\",\"@version\"],...
    ```
1. hit enter to send the request
1. download csv report

we understand that this is not ideal, we'll definitely need a better long term solution, but for now you can try this and see if it works

**Comment by joshuali925** [comment]
i'll close here since the issue is in dashboards-reporting. let's use https://github.com/opensearch-project/dashboards-reporting/issues/335 for tracking this issue
