### ISSUE TITLE
[BUG] not possible to export csv of more than 10000 lines

### ISSUE THREAD

**Issue by tibz7** [opensearch-project/reporting#721]
**What is the bug?**
It is not possible to export csv with more than 10000 lines. This is however an important feature for many people. It is also very counter intuitive as you expect to get the full query. And there is no information about that anywhere.

**Comment by mhoydis13** [comment]
Any update on this?  
https://forum.opensearch.org/t/export-csv-for-more-then-10000-lines/7074

**Comment by Swiddis** [comment]
Also talked about here and in a few other issues, going to close this one as a duplicate: https://github.com/opensearch-project/dashboards-reporting/issues/328
