### ISSUE TITLE
[BUG] Flaky Report IT tests

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/reporting#752]
**What is the bug?**
[A clear and concise description of the bug.](https://github.com/opensearch-project/reporting/actions/runs/6006247230/job/16290451050?pr=733)
Possibly related to seg rep #719 

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by joshuali925** [comment]
pending https://github.com/opensearch-project/reporting/pull/942

**Comment by mengweieric** [comment]
https://github.com/opensearch-project/reporting/pull/942 merged
